"""initial schema

Revision ID: eb9ff072d114
Revises: 
Create Date: 2026-09-06 20:07:58.953848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9ff072d114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_brand', sa.String(), nullable=False),
    sa.Column('brand_logo_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('required_biome', sa.String(), nullable=True),
    sa.Column('required_steps', sa.Integer(), nullable=False),
    sa.Column('required_elevation_gain_m', sa.Float(), nullable=False),
    sa.Column('target_geofence_center', sa.JSON(), nullable=True),
    sa.Column('reward_pool_usdc', sa.Float(), nullable=False),
    sa.Column('reward_grln_tokens', sa.Integer(), nullable=False),
    sa.Column('reward_gear_skin_id', sa.String(), nullable=True),
    sa.Column('max_claimants', sa.Integer(), nullable=False),
    sa.Column('current_claimants', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_quests_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_quests_id'), ['id'], unique=False)

    op.create_table('clan_raid_bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_name', sa.String(), nullable=False),
    sa.Column('total_health_steps', sa.Integer(), nullable=False),
    sa.Column('current_health_steps', sa.Integer(), nullable=False),
    sa.Column('is_defeated', sa.Boolean(), nullable=False),
    sa.Column('reward_grln_pool', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clan_raid_bosses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_raid_bosses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_raid_bosses_is_defeated'), ['is_defeated'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('solana_wallet', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_device_verified', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('streak_freeze_count', sa.Integer(), nullable=False),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('last_active_date', sa.DateTime(), nullable=False),
    sa.Column('stamina_balance', sa.Integer(), nullable=False),
    sa.Column('grln_token_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_solana_wallet'), ['solana_wallet'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_activity_uuid', sa.String(length=64), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('start_elevation_m', sa.Float(), nullable=False),
    sa.Column('max_elevation_m', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=False),
    sa.Column('detected_biome', sa.String(), nullable=False),
    sa.Column('weather_condition', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('cadence_variance', sa.Float(), nullable=False),
    sa.Column('hardware_signature_valid', sa.Boolean(), nullable=False),
    sa.Column('ble_pack_count', sa.Integer(), nullable=False),
    sa.Column('flagged_reason', sa.String(), nullable=True),
    sa.Column('steps_credited', sa.Integer(), nullable=False),
    sa.Column('stamina_credited', sa.Integer(), nullable=False),
    sa.Column('xp_credited', sa.Integer(), nullable=False),
    sa.Column('route_geojson', sa.JSON(), nullable=True),
    sa.Column('h3_hex_indexes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_activity_uuid', name='uq_activity_user_client_uuid')
    )
    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_records_client_activity_uuid'), ['client_activity_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_user_id'), ['user_id'], unique=False)

    op.create_table('gremlins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('next_level_xp', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('is_sleeping', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('biome_affinity', sa.String(), nullable=False),
    sa.Column('biome_resonance_score', sa.Float(), nullable=False),
    sa.Column('avatar_image_url', sa.String(), nullable=False),
    sa.Column('equipped_gear', sa.JSON(), nullable=False),
    sa.Column('visual_traits', sa.JSON(), nullable=False),
    sa.Column('solana_cnft_id', sa.String(), nullable=True),
    sa.Column('tree_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_fed_at', sa.DateTime(), nullable=False),
    sa.Column('last_evolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solana_cnft_id')
    )
    with op.batch_alter_table('gremlins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gremlins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gremlins_owner_id'), ['owner_id'], unique=False)

    op.create_table('nft_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('story_note', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('original_photo_url', sa.String(), nullable=False),
    sa.Column('rendered_art_url', sa.String(), nullable=False),
    sa.Column('arweave_metadata_uri', sa.String(), nullable=True),
    sa.Column('solana_asset_id', sa.String(), nullable=True),
    sa.Column('mint_tx_hash', sa.String(), nullable=True),
    sa.Column('is_onchain', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_records.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id'),
    sa.UniqueConstraint('solana_asset_id')
    )
    with op.batch_alter_table('nft_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_metadata_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_metadata_id'), ['id'], unique=False)

    op.create_table('nft_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('price_usd_approx', sa.Float(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nft_id'], ['nft_metadata.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nft_id')
    )
    with op.batch_alter_table('nft_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_listings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_listings_is_sold'), ['is_sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_listings_listed_at'), ['listed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_listings_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nft_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_listings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_nft_listings_listed_at'))
        batch_op.drop_index(batch_op.f('ix_nft_listings_is_sold'))
        batch_op.drop_index(batch_op.f('ix_nft_listings_id'))

    op.drop_table('nft_listings')
    with op.batch_alter_table('nft_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_nft_metadata_creator_id'))

    op.drop_table('nft_metadata')
    with op.batch_alter_table('gremlins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gremlins_owner_id'))
        batch_op.drop_index(batch_op.f('ix_gremlins_id'))

    op.drop_table('gremlins')
    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_records_started_at'))
        batch_op.drop_index(batch_op.f('ix_activity_records_id'))
        batch_op.drop_index(batch_op.f('ix_activity_records_ended_at'))
        batch_op.drop_index(batch_op.f('ix_activity_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_records_client_activity_uuid'))

    op.drop_table('activity_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_solana_wallet'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('clan_raid_bosses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_raid_bosses_is_defeated'))
        batch_op.drop_index(batch_op.f('ix_clan_raid_bosses_id'))

    op.drop_table('clan_raid_bosses')
    with op.batch_alter_table('brand_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_quests_id'))
        batch_op.drop_index(batch_op.f('ix_brand_quests_expires_at'))

    op.drop_table('brand_quests')
    # ### end Alembic commands ###
